# Generated by Django 3.1.7 on 2021-03-26 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210326_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Recipe Title')),
                ('time_minutes', models.PositiveSmallIntegerField(verbose_name='Recipe Minutes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Recipe Price')),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Recipe Date')),
                ('ingredients', models.ManyToManyField(related_name='ingredients_recipes', to='core.Ingredient', verbose_name='Recipe Ingredients')),
                ('tags', models.ManyToManyField(related_name='tags_recipes', to='core.Tag', verbose_name='Recipe Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Recipe User')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ['-created_at'],
            },
        ),
    ]
